# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://ianmellis.github.io/
baseurl: 
title: Ian Mellis
author: Ian Mellis
description: Personal blog and resume
avatar: iamellis_photo2.png
email: ian.mellis@gmail.com
github: ianmellis # username
twitter: ian_mellis
googlescholar: 9IELUHoAAAAJ
#linkedin: username
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-131025114-1


# needed for travis-ci build
exclude: [vendor]
